import pytest
from httpx import AsyncClient
from unittest.mock import AsyncMock, patch
import json
import pytest_asyncio


from app.config import settings
from app.models.job import TriageRequest, TriageItem, TriageResponse
from app.services.prompt_builder import TRIAGE_PROMPT, build_triage_messages

# Mock ModelRouter for AI calls
@pytest.fixture
def mock_model_router():
    with patch("app.services.ai_worker.get_model_router") as mock_get_router:
        mock_router = AsyncMock()
        mock_get_router.return_value = mock_router
        yield mock_router

# Client for testing FastAPI endpoints
async def client(app):
    async with AsyncClient(app=app, base_url="http://test") as ac:
        yield ac

# Test cases for the /triage endpoint
@pytest.mark.asyncio
async def test_triage_endpoint_unauthorized(client: AsyncClient):
    response = await client.post("/triage", json={"raw_text": "test"})
    assert response.status_code == 401
    assert response.json() == {"detail": "Unauthorized"}

@pytest.mark.asyncio
async def test_triage_endpoint_missing_raw_text(client: AsyncClient):
    headers = {"X-Internal-API-Token": "test-token"}
    response = await client.post("/triage", json={}, headers=headers)
    assert response.status_code == 422 # FastAPI validation error for missing field

@pytest.mark.asyncio
async def test_triage_endpoint_valid_request_empty_ai_response(
    client: AsyncClient, mock_model_router: AsyncMock
):
    # Mock AI to return empty content
    mock_model_router.route.return_value = AsyncMock(content="", model="mock", prompt_tokens=0, completion_tokens=0)
    
    headers = {"X-Internal-API-Token": "test-token"}
    request_data = {"raw_text": "Hello world"}
    response = await client.post("/triage", json=request_data, headers=headers)
    
    assert response.status_code == 500
    assert "AI returned invalid JSON structure" in response.json()["detail"]

@pytest.mark.asyncio
async def test_triage_endpoint_valid_request_malformed_json_ai_response(
    client: AsyncClient, mock_model_router: AsyncMock
):
    # Mock AI to return malformed JSON
    mock_model_router.route.return_value = AsyncMock(content="not json", model="mock", prompt_tokens=0, completion_tokens=0)
    
    headers = {"X-Internal-API-Token": "test-token"}
    request_data = {"raw_text": "Hello world"}
    response = await client.post("/triage", json=request_data, headers=headers)
    
    assert response.status_code == 500
    assert "AI returned invalid JSON structure" in response.json()["detail"]

@pytest.mark.asyncio
async def test_triage_endpoint_valid_request_ai_response_with_markdown(
    client: AsyncClient, mock_model_router: AsyncMock
):
    mock_ai_content = """```json
    {
      "items": [
        {
          "subject": "Test Sub",
          "summary": "Test Sum",
          "urgency": "Medium",
          "category": "Work",
          "smart_replies": ["ok", "cancel"],
          "action_items": ["do this"],
          "original_segment": "original"
        }
      ]
    }
    ```"""
    mock_model_router.route.return_value = AsyncMock(content=mock_ai_content, model="mock", prompt_tokens=10, completion_tokens=20)
    
    headers = {"X-Internal-API-Token": "test-token"}
    request_data = {"raw_text": "Email 1 content"}
    response = await client.post("/triage", json=request_data, headers=headers)
    
    assert response.status_code == 200
    assert response.json()["items"][0]["subject"] == "Test Sub"
    assert response.json()["items"][0]["urgency"] == "Medium"

@pytest.mark.asyncio
async def test_triage_endpoint_valid_request_successful_triage(
    client: AsyncClient, mock_model_router: AsyncMock
):
    mock_triage_item = TriageItem(
        id="123", # ID is generated by Pydantic model
        subject="Meeting Request",
        summary="Request to schedule a meeting next week.",
        urgency="High",
        category="Client",
        smart_replies=["Confirm availability", "Suggest alternative times"],
        action_items=["Check calendar", "Propose times"],
        original_segment="Hi team, I'd like to schedule a meeting next week to discuss the project."
    )
    mock_ai_content = TriageResponse(items=[mock_triage_item]).model_dump_json()
    mock_model_router.route.return_value = AsyncMock(content=mock_ai_content, model="mock", prompt_tokens=10, completion_tokens=20)
    
    headers = {"X-Internal-API-Token": "test-token"}
    request_data = {"raw_text": "Hi team, I'd like to schedule a meeting next week to discuss the project."}
    response = await client.post("/triage", json=request_data, headers=headers)
    
    assert response.status_code == 200
    parsed_response = TriageResponse.model_validate(response.json())
    assert len(parsed_response.items) == 1
    assert parsed_response.items[0].subject == "Meeting Request"
    assert parsed_response.items[0].urgency == "High"
    assert "Check calendar" in parsed_response.items[0].action_items

# Test cases for prompt builder utility
def test_build_triage_messages():
    raw_text = "Hello world email 1. Another email."
    messages = build_triage_messages(raw_text)
    
    assert len(messages) == 2
    assert messages[0]["role"] == "system"
    assert "Inbox Triage Engine" in messages[0]["content"]
    assert messages[1]["role"] == "user"
    assert raw_text in messages[1]["content"]
    assert "JSON Output:" in messages[1]["content"]